[pytest]
addopts = -q --html=test-artifacts/reports/pytest-report.html --self-contained-html --output=test-artifacts/traces --screenshot=only-on-failure --video=retain-on-failure --tracing=retain-on-failure
python_files = test_*.py
testpaths = tests_logic tests_e2e
